import { SUPABASE_URL, SUPABASE_ANON_KEY } from './config.js?v=103';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const login = document.querySelector('#login'), dashboard = document.querySelector('#dashboard'), logout = document.querySelector('#logout'), changePassword = document.querySelector('#change-password'), passwordDialog = document.querySelector('#password-editor'), passwordForm = document.querySelector('#password-form');
const status = document.querySelector('#login-form .status');
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) status.textContent = 'ยังไม่ได้ตั้งค่า Supabase ใน js/config.js';
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
let tab = 'projects', items = [];
const labels = { projects: 'ผลงานที่ดูแล', services: 'บริการ', leads: 'รายการลูกค้า', settings: 'ข้อความหน้าเว็บ', profiles: 'ผู้ดูแลระบบ' };
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[char]);
async function guard() { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from('profiles').select('is_admin').eq('id', user.id).single(); if (!profile?.is_admin) { await supabase.auth.signOut(); status.textContent = 'บัญชีนี้ไม่มีสิทธิ์ผู้ดูแล'; return; } login.hidden = true; dashboard.hidden = false; logout.hidden = false; changePassword.hidden = false; load(); }
async function load() { document.querySelector('#panel-title').textContent = labels[tab]; const add = document.querySelector('#new-item'); add.hidden = tab === 'leads'; add.textContent = tab === 'settings' ? 'บันทึกข้อความ' : tab === 'profiles' ? '+ เพิ่มผู้ดูแล' : '+ เพิ่มรายการ'; const table = tab === 'settings' ? 'site_settings' : tab; const query = (tab === 'leads' || tab === 'profiles') ? supabase.from(table).select('*').order('created_at', { ascending: false }) : supabase.from(table).select('*').order('sort_order'); const { data, error } = await query; items = data || []; const out = document.querySelector('#admin-content'); if (error) { out.textContent = error.message; return; } if (tab === 'settings') { const hero = items.find((x) => x.key === 'hero_text')?.value?.text || ''; out.innerHTML = `<label>ข้อความหน้าแรก<textarea id="hero-setting">${escapeHtml(hero)}</textarea></label><button class="button" id="save-setting">บันทึกข้อความ</button>`; document.querySelector('#save-setting').onclick = saveSetting; return; } out.innerHTML = items.length ? items.map(row).join('') : '<p class="muted">ยังไม่มีข้อมูล</p>'; }
function row(item) { const detail = tab === 'leads' ? `${item.contact} · ${item.service}` : tab === 'profiles' ? item.email : item.description || item.category || ''; const visibility = item.is_published === false ? 'ซ่อนจากเว็บ' : tab === 'leads' ? (item.status || 'ใหม่') : tab === 'profiles' ? 'ผู้ดูแล' : 'แสดงบนเว็บ'; return `<div class="data-row" data-id="${item.id}"><div><b>${escapeHtml(item.name || item.title || item.email)}</b><span class="muted">${escapeHtml(tab === 'leads' ? item.message : detail)}</span></div><div class="muted">${escapeHtml(detail)}</div><span class="tag">${escapeHtml(visibility)}</span><div class="row-actions">${tab === 'profiles' ? '' : `<button data-action="edit">${tab === 'leads' ? 'อัปเดต' : 'แก้ไข'}</button>${tab !== 'leads' ? '<button data-action="delete">ลบ</button>' : ''}`}</div></div>`; }
document.querySelector('#login-form').addEventListener('submit', async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); status.textContent = 'กำลังเข้าสู่ระบบ...'; const { error } = await supabase.auth.signInWithPassword({ email: f.get('email'), password: f.get('password') }); if (error) { status.textContent = error.message === 'Invalid login credentials' ? 'อีเมลหรือรหัสผ่านไม่ถูกต้อง' : `เข้าสู่ระบบไม่สำเร็จ: ${error.message}`; return; } guard(); });
logout.onclick = async () => { await supabase.auth.signOut(); location.reload(); };
changePassword.onclick = () => { passwordForm.reset(); passwordDialog.showModal(); };
passwordForm.addEventListener('submit', async (e) => { e.preventDefault(); const f = new FormData(passwordForm); const currentPassword = f.get('current_password'); const newPassword = f.get('new_password'); const confirmPassword = f.get('confirm_password'); const passwordStatus = document.querySelector('#password-status'); if (newPassword.length < 12) { passwordStatus.textContent = 'รหัสผ่านใหม่ต้องมีอย่างน้อย 12 ตัวอักษร'; return; } if (newPassword !== confirmPassword) { passwordStatus.textContent = 'ยืนยันรหัสผ่านใหม่ไม่ตรงกัน'; return; } passwordStatus.textContent = 'กำลังบันทึก...'; const { error } = await supabase.auth.updateUser({ password: newPassword, current_password: currentPassword }); if (error) { passwordStatus.textContent = `เปลี่ยนรหัสผ่านไม่สำเร็จ: ${error.message}`; return; } passwordDialog.close(); alert('เปลี่ยนรหัสผ่านเรียบร้อยแล้ว'); });
const adminTab = document.createElement('button'); adminTab.dataset.tab = 'profiles'; adminTab.textContent = 'ผู้ดูแล'; document.querySelector('.tabs').append(adminTab);
document.querySelectorAll('.tabs button').forEach((b) => b.onclick = () => { tab = b.dataset.tab; document.querySelectorAll('.tabs button').forEach((x) => x.classList.toggle('active', x === b)); load(); });
const dialog = document.querySelector('#editor'), form = document.querySelector('#edit-form');
document.querySelector('#new-item').onclick = () => { if (tab === 'settings') { document.querySelector('#save-setting')?.click(); return; } if (tab === 'profiles') { inviteAdmin(); return; } form.reset(); form.elements.id.value = ''; document.querySelector('#editor-title').textContent = 'เพิ่ม ' + labels[tab]; document.querySelectorAll('.project-only').forEach((x) => x.hidden = tab !== 'projects'); dialog.showModal(); };
document.querySelector('#admin-content').onclick = async (e) => { const button = e.target.closest('button[data-action]'); if (!button) return; const item = items.find((x) => x.id === button.closest('[data-id]').dataset.id); if (button.dataset.action === 'delete') { if (confirm(`ลบ “${item.title}” หรือไม่?`)) { await supabase.from(tab).delete().eq('id', item.id); load(); } return; } form.elements.id.value = item.id; form.elements.title.value = item.title || item.name; form.elements.description.value = item.description || item.message || ''; form.elements.category.value = item.category || ''; form.elements.image_url.value = item.image_url || ''; form.elements.is_published.checked = item.is_published !== false; document.querySelectorAll('.project-only').forEach((x) => x.hidden = tab !== 'projects'); dialog.showModal(); };
form.addEventListener('submit', async (e) => { e.preventDefault(); if (e.submitter.value !== 'save') return; const f = new FormData(form); const values = tab === 'leads' ? { status: 'ติดต่อแล้ว' } : { title: f.get('title'), description: f.get('description'), category: f.get('category'), image_url: f.get('image_url') || null, is_published: f.get('is_published') === 'on' }; const id = f.get('id'); const request = id ? supabase.from(tab).update(values).eq('id', id) : supabase.from(tab).insert(values); const { error } = await request; if (error) alert(error.message); dialog.close(); load(); });
async function saveSetting() { const text = document.querySelector('#hero-setting').value; const { error } = await supabase.from('site_settings').upsert({ key: 'hero_text', value: { text } }); if (error) alert(error.message); else alert('บันทึกแล้ว'); }
async function inviteAdmin() { const email = prompt('อีเมลของผู้ดูแลคนใหม่'); if (!email) return; const { error } = await supabase.functions.invoke('create-admin', { body: { email } }); if (error) alert('เพิ่มผู้ดูแลไม่สำเร็จ: ' + error.message); else { alert('ส่งคำเชิญให้ ' + email + ' แล้ว'); tab = 'profiles'; load(); } }
guard();
